version: "3.7"

networks:
  app_network:
    driver: bridge

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - C:\bancoDeDados\projeto2:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    depends_on:
      - database_ignite
    networks:
      - app_network
    environment:
      - DB_HOST=database_ignite
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100